version: "3.7"
services:
  # nginx:
  #   container_name: nginx-proxy
  #   image: nginx:1.24-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - ./deployment/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 2567:2567
  #     # - 3000:3000
  #   networks:
  #     - coly-net

  mongo:
    image: mongo:4.2
    container_name: mongo_c3
    restart: always
    volumes:
      - mongo_db:/data/db
      - ./deployment/init-database.js:/docker-entrypoint-initdb.d/init-database.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=publisher
      - MONGO_INITDB_ROOT_PASSWORD=pwd
    ports:
      - 27017:27017
    networks:
      - coly-net

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - coly-net

  multiplay:
    container_name: multiplay
    build:
      dockerfile: ./Dockerfile
    # deploy:
    #   mode: replicated
    #   replicas: 1
    ports:
      - 2567
    depends_on:
      - redis
    networks:
      - coly-net

volumes:
  mongo_db:

networks:
  coly-net:
    driver: "bridge"
